/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KYCRegistry } from "./KYCRegistry";
export type { Marketplace } from "./Marketplace";
export type { MockERC20 } from "./MockERC20";
export type { PixelEstate } from "./PixelEstate";
export type { PropertyRegistry } from "./PropertyRegistry";
export type { RentalDistributor } from "./RentalDistributor";
export type { SaleVoting } from "./SaleVoting";
